# Generated by Django 4.2.3 on 2023-07-27 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0002_remove_users_email_remove_users_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
