# Generated by Django 4.2.3 on 2023-07-30 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0005_berries_decor_layer_shape_topping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 17, 7, 49, 805297, tzinfo=datetime.timezone.utc), verbose_name='Дата создания заказа'),
        ),
    ]
