# Generated by Django 4.2.3 on 2023-07-31 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0006_alter_order_init_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bake_cake_bot.berries'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bake_cake_bot.decor'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Надпись на торте'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bake_cake_bot.topping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 10, 46, 31, 430605, tzinfo=datetime.timezone.utc), verbose_name='Дата создания заказа'),
        ),
    ]
