# Generated by Django 4.2.3 on 2023-07-31 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0007_alter_cake_berries_alter_cake_decor_alter_cake_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 11, 23, 43, 194856, tzinfo=datetime.timezone.utc), verbose_name='Дата создания заказа'),
        ),
    ]
