# Generated by Django 4.2.3 on 2023-08-01 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0024_alter_order_init_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berries',
            options={'verbose_name': 'Ягода', 'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'verbose_name': 'Декор', 'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name': 'Слой', 'verbose_name_plural': 'Слои'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'Топинг', 'verbose_name_plural': 'Топинги'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
        migrations.AlterField(
            model_name='order',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 7, 49, 31, 767244, tzinfo=datetime.timezone.utc), verbose_name='Дата создания заказа'),
        ),
    ]
