# Generated by Django 4.2.3 on 2023-08-01 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0025_alter_berries_options_alter_cake_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='order',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 10, 45, 14, 235720), verbose_name='Дата создания заказа'),
        ),
    ]
