# Generated by Django 4.2.3 on 2023-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitly_Shortner', '0002_alter_shortenedlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedlink',
            name='click_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество кликов'),
        ),
    ]
