# Generated by Django 4.2.3 on 2023-07-31 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bitly_Shortner', '0003_shortenedlink_click_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitlyShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, unique=True)),
                ('shortened_link', models.URLField(max_length=2000, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shortened_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkclick', to='Bitly_Shortner.bitlyshortenedlink')),
            ],
        ),
        migrations.DeleteModel(
            name='ShortenedLink',
        ),
    ]
