# Generated by Django 4.2.3 on 2023-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitly_Shortner', '0004_bitlyshortenedlink_linkclick_delete_shortenedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField(verbose_name='Оригинальная ссылка')),
                ('shortened_link', models.URLField(blank=True, verbose_name='Сокращенная ссылка')),
                ('link_title', models.CharField(blank=True, max_length=200, verbose_name='Название ссылки')),
                ('click_count', models.IntegerField(default=0, editable=False, verbose_name='Количество кликов')),
            ],
            options={
                'verbose_name': 'Сокращенная ссылка',
                'verbose_name_plural': 'Сокращенные ссылки',
            },
        ),
        migrations.RemoveField(
            model_name='linkclick',
            name='shortened_link',
        ),
        migrations.DeleteModel(
            name='BitlyShortenedLink',
        ),
        migrations.DeleteModel(
            name='LinkClick',
        ),
    ]
