# Generated by Django 4.2.3 on 2023-07-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitly_Shortner', '0005_shortenedlink_remove_linkclick_shortened_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='click_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество кликов'),
        ),
    ]
